### ISSUE TITLE
Wildcard support for manual templates

### ISSUE THREAD

**Issue by cm090** [cm090/gradescope-autograder#22]
Right now, manual autograders check for file existence by looking at the exact filename. This does not allow for wildcards, causing problems if a student names their file different from what the instructions recommend. Students receive false negatives on the missing files check even though they submitted all the required files. For this feature, you will update both manual templates to support wildcards in the format `*.java`, `*.png`, and so on. You can expect each wildcard begins with a single star, followed by a dot and the file extension. When this is encountered, the autograder will search for files in the submission directory that end with the specified file extension. If at least one is found, the check passes. Otherwise, alert the student of a missing file.

This feature is partially implemented on the HWQuizQuestions autograder, which you can download [here](https://www.gradescope.com/courses/742123/assignments/4142003/configure_autograder). The goal is to add support for any wildcard provided in the `config.json` file list.

If you have time, have the wildcard search ignore other files from the configuration. For example, if the files list includes `MyClass.java` and `*.java`, the autograder will ignore `MyClass.java` when searching for matches.

**Comment by taborinstein** [comment]
Working on this~

**Comment by cm090** [comment]
Unassigning this issue for the end of the quarter

**Comment by cm090** [comment]
General wildcard support is present with #27. Will continue to exclude explicitly mentioned files from the wildcard search.
