### ISSUE TITLE
Ignore case sensitivity for manual templates

### ISSUE THREAD

**Issue by cm090** [cm090/gradescope-autograder#23]
Manual autograder templates currently expect a predefined list of files to be uploaded where their names match exactly. This is a problem if we expect `MyClass.java` and a student uploads `myclass.JAVA`, for example. We want to compare files strictly in lowercase to prevent false negatives. Your implementation should be robust enough to eventually handle converting wildcards to lowercase without much modification.

**Comment by spectre256** [comment]
Looks like I was supposed to leave a comment here. Sorry!
